server:
  port: 9001


spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zyshengcode/webproject_ssm
          username: zyshengha@outlook.com
          password: Zhanghan12
          timeout: 5
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
